// The reference app's API surface, mapped onto the vuapp Worker backend.
//
// Generated by tools/orich from the decompiled bundle: every name below is a
// function the ported pages actually call, so the screens keep reading like
// the original while the requests go to the vuapp API.

import { get, post, put, del, setTokens, clearTokens, readRefresh } from './request';

/** POST /index/accountedit */
export const AccountEdit = (d = {}) => put('/api/account/username', { username: d.name || d.username });

/** POST /index/duobaoitemlistnew */
export const ActiveList = (d = {}) => get('/api/goods', d);

/** POST /index/addressadd */
export const AddAddress = (d = {}) => post('/api/addresses', d);

/** POST /index/addorder */
export const AddOrder = (d = {}) => post('/api/orders', d);

/** POST /index/addresslist */
export const AddressList = () => get('/api/addresses');

/** POST /index/addressdel */
export const DelAddress = (d = {}) => (d.id ? del('/api/addresses/' + d.id) : Promise.resolve({}));

/** POST /index/duobaoitem */
export const DuobaoItem = (d = {}) => get('/api/goods', d);

/** POST /index/duobaoitem1 */
export const DuobaoSwiperItem = (d = {}) => get('/api/goods', d);

/** POST /index/addresschangedefault */
export const EditAccount = (d = {}) => (d.id ? put('/api/addresses/' + d.id, { ...d, is_default: 1 }) : Promise.resolve({}));

/** POST /index/addressedit */
export const EditAddress = (d = {}) => (d.id ? put('/api/addresses/' + d.id, d) : post('/api/addresses', d));

/** POST /index/kind */
export const GKind = () => get('/api/goods');

/** POST /index/duobaoitemlottery */
export const GetLottery = (d = {}) => (d.id ? post('/api/goods/' + d.id + '/draw', d) : Promise.resolve({ list: [] }));

/** POST /index/getlotteryresult */
export const GetResult = (d = {}) => (d.id ? get('/api/orders/' + d.id + '/ranking') : Promise.resolve({ list: [] }));

/** POST /index/duobaoitemjoinlist */
export const GoodsBuyDetail = (d = {}) => (d.id ? get('/api/goods/' + d.id) : get('/api/goods'));

/** POST /index/duobaoitemdetail */
export const GoodsDetail = (d = {}) => (d.id ? get('/api/goods/' + d.id) : get('/api/goods'));

/** POST /index/duobaoitemhistory */
export const GoodsHisDetail = (d = {}) => (d.id ? get('/api/goods/' + d.id) : get('/api/goods'));

/** POST /index/duobaoitemlist */
export const GoodsList = (d = {}) => get('/api/goods', d);

/** POST /index/duobaoitemshare */
export const GoodsShareDetail = (d = {}) => (d.id ? get('/api/goods/' + d.id) : get('/api/goods'));

/** POST /index/index */
export const Index = () =>
    get('/api/home').then((r) => {
      const home = r || {};
      return {
        title: 'vuapp',
        bannerlist: (home.banners || []).map((b) => ({
          imageurl: b.image,
          type: b.type || '',
          url: b.link || '',
        })),
        navigationlist: home.navigation || [],
        system: home.system || { whatsapp: '', customercontent: '' },
        ...home,
      };
    });

/** POST /index/itemshare */
export const ItemShare = (d = {}) => post('/api/orders', d);

/** POST /index/login */
export const Login = (d = {}) =>
    post('/api/auth/login', { phone: d.mobile || d.phone, code: d.code, invite: d.invitecode }).then((r) => {
      if (r && r.access) setTokens(r.access, r.refresh);
      return { ...r, token: r && r.access };
    });

/** POST /index/logout */
export const Logout = () => post('/api/auth/logout', { refresh: readRefresh() }).then((r) => { clearTokens(); return r; });

/** POST /index/ordernews */
export const OrderNews = () => get('/api/notices');

/** POST /index/runoobdetail */
export const RunoobDetail = (d = {}) => get('/api/pages/' + (d.slug || d.id || 'about'));

/** POST /index/sendverify */
export const SendVerify = (d = {}) => post('/api/auth/sendverify', { phone: d.mobile || d.phone });

/** POST /index/getsystem */
export const SystemInfo = () =>
    Promise.resolve({
      title: 'vuapp',
      taskstatus: 1,
      image: '',
      version: [],
      tablist: [],
    });

/** POST /index/userbalance */
export const UserBalance = () => get('/api/wallet');

/** POST /index/useraccount */
export const UserInfo = () => get('/api/account');

/** POST /index/userjoin */
export const UserJoin = (d = {}) => get('/api/orders', d);

/** POST /index/winnerlist */
export const WinnerList = (d = {}) => get('/api/winners', d);

/** POST /index/activitydetail */
export const activityDetail = (d = {}) => get('/api/prizes', d);

/** POST /index/addrechargepay2 */
export const addRechargePay = (d = {}) => post('/api/recharge', d);

/** POST /index/bankdel */
export const bankDel = (d = {}) => (d.id ? del('/api/beneficiaries/' + d.id) : Promise.resolve({}));

/** POST /index/banklist */
export const bankList = () => get('/api/beneficiaries');

/** POST /index/bankadd */
export const bankadd = (d = {}) => post('/api/beneficiaries', d);

/** POST /index/cashlist */
export const cashList = () => get('/api/withdraw/records');

/** POST /index/chlwhatsapp */
export const chlWhatsApp = () => get('/api/pages/support');

/** POST /index/financeBuy */
export const financeBuy = (d = {}) => post('/api/finance/order', d);

/** POST /index/financeDetail */
export const financeDetail = (d = {}) => (d.id ? get('/api/finance/' + d.id) : get('/api/finance'));

/** POST /index/financeDetailHistory */
export const financeDetailHistory = (d = {}) => (d.id ? get('/api/finance/' + d.id) : get('/api/finance'));

/** POST /index/financeList */
export const financeList = () => get('/api/finance');

/** POST /index/financeOrderRecent */
export const financeOrderRecent = () => get('/api/finance/orders/mine');

/** POST /index/getactivity */
export const getActivity = () => get('/api/prizes');

/** POST /index/getanswer */
export const getAnswer = (d = {}) => (d.id || d.topic ? get('/api/help/' + (d.id || d.topic)) : get('/api/help'));

/** POST /index/gettitle */
export const getTitle = () => get('/api/help');

/** POST /index/getUserAfs */
export const getUserAfs = () => get('/api/payments');

/** POST /index/itemdefaultaddr */
export const itemDefaultAddr = () => get('/api/addresses');

/** POST /index/itemedit */
export const itemEdit = (d = {}) => post('/api/orders', d);

/** POST /index/joinactivity */
export const joinActivity = (d = {}) => post('/api/game/play', d);

/** POST /index/luckyBuy */
export const luckyBuy = (d = {}) => post('/api/game/play', d);

/** POST /index/luckyList */
export const luckyList = () => get('/api/prizes');

/** POST /index/luckyNow */
export const luckyNow = () => get('/api/prizes');

/** POST /index/luckyOrderList */
export const luckyOrderList = () => get('/api/orders', { kind: 'lucky' });

/** POST /index/myFinanceList */
export const myFinanceList = () => get('/api/finance/orders/mine');

/** POST /index/myteam */
export const myTeam = () => get('/api/team');

/** POST /index/mywinner */
export const myWinner = (d = {}) => get('/api/my-shares', d);

/** POST /index/itemdetail */
export const orderDetail = (d = {}) => (d.id ? get('/api/orders/' + d.id) : get('/api/orders'));

/** POST /index/rechargelist */
export const rechargeList = () => get('/api/recharge/records');

/** POST /index/systemservice */
export const systemService = () => get('/api/pages/support');

/** POST /index/taskList */
export const taskList = () => get('/api/tasks');

/** POST /index/taskReceive */
export const taskReceive = (d = {}) => (d.id ? post('/api/tasks/' + d.id + '/claim', d) : Promise.resolve({}));

/** POST /index/useraccount */
export const userAccount = () => get('/api/account');

/** POST /index/userconsume */
export const userConsume = () => get('/api/wallet/transactions');

/** POST /index/userinvitelist */
export const userInviteList = () => get('/api/referrals');

/** POST /index/userinvitetop */
export const userInviteTop = () => get('/api/referrals');

/** POST /index/useritem */
export const userOrder = (d = {}) => get('/api/orders', d);

/** POST /index/userrebatelist */
export const userRebateList = () => get('/api/wallet/transactions');

/** POST /index/usershare */
export const userShare = () => get('/api/my-shares');

/** POST /index/userwithdraw */
export const userWithdraw = (d = {}) => post('/api/withdraw', d);

// --- not implemented on the vuapp backend -------------------------------
//
// These reference endpoints have no vuapp counterpart yet. They resolve to
// an empty result so the screens that call them still render.
// Resolves to an empty object rather than null: the screens read
// properties straight off the response, so `{}` degrades to empty
// state while null would throw.
const notImplemented = (name) => {
  if (!notImplemented.warned) notImplemented.warned = {};
  if (!notImplemented.warned[name]) {
    notImplemented.warned[name] = true;
    console.warn('[api] ' + name + ' is not implemented on the vuapp backend');
  }
  return Promise.resolve({});
};

/** POST /index/getlotterytime (lottery countdown feed) */
export const GetTime = () => notImplemented('GetTime');
/** POST /index/getnumbermax (per-user slot cap) */
export const NumberMax = () => notImplemented('NumberMax');
/** POST /index/addorderpay (order payment intent) */
export const addOrderPay = () => notImplemented('addOrderPay');
/** POST /index/bankedit (beneficiary edit) */
export const bankEdit = () => notImplemented('bankEdit');
/** POST /index/editAfStatus (payment method toggle) */
export const editAfStatus = () => notImplemented('editAfStatus');
/** POST /index/price (price table) */
export const gPrice = () => notImplemented('gPrice');
/** POST /index/paystatus (payment status poll) */
export const payStatus = () => notImplemented('payStatus');
/** POST /index/vipBuy (vip purchase) */
export const vipBuy = () => notImplemented('vipBuy');
/** POST /index/vip (vip tiers) */
export const vipLevel = () => notImplemented('vipLevel');
