// The reference app's API surface, mapped onto the vuapp Worker backend.
//
// Generated by tools/orich from the decompiled bundle: every name below is a
// function the ported pages actually call, so the screens keep reading like
// the original while the requests go to the vuapp API.

import { get, post, put, del, setTokens, clearTokens, readRefresh } from './request';

// --- response adapters ----------------------------------------------------
//
// The Worker returns its own field names and integer minor units; the ported
// screens read the reference's names and major-unit values. Convert here, never
// in a screen, so the pages stay comparable with the reference.

const major = (minor) => (minor == null ? 0 : Number(minor) / 100);
const nowSec = () => Math.floor(Date.now() / 1000);

/** A goods row -> the reference's group-buy item shape. */
const goodsItem = (g) => {
  const it = g || {};
  return {
    ...it,
    id: it.id,
    name: it.title,
    iconurl: it.image,
    imageurl: it.image,
    unit_price: major(it.price_minor),
    price: major(it.price_minor),
    allprice: major(it.market_price_minor),
    current_buy: it.filled_slots || 0,
    max_buy: it.total_slots || 0,
    issue: it.issue,
    // the reference used 1 = joinable, 2 = drawn, 3 = counting down
    has_lottery: it.status === 'active' ? 1 : 2,
    lottery: it.end_at,
    success: it.end_at,
    nowtime: nowSec(),
    countdown: '',
    // participant avatars / count: the reference showed who had joined. No
    // equivalent on the vuapp backend yet - empty arrays so the strip renders
    // blank instead of the template reading a length off undefined.
    userimgurl: [],
    usernumber: 0,

    // --- detail-screen fields ---
    galleryurl: it.gallery || (it.image ? [it.image] : []),
    description: it.description || '',
    current_price: major(it.price_minor),
    type: it.category || '',
    newid: it.id,
    normal: 1,
    nickname: '',
    // draw bookkeeping the reference displayed; no equivalent yet
    getnumber: 0,
    getnumberall: 0,
    getnumbercount: 0,
    lottery_time: it.end_at || 0,
    lottery_sn: '',
    lotteryallocation: [],
    fair_sn_local: '',
    faq_url: '',
    del_type: 0,
    auto_return: 0,
    max_return: 0,
  };
};

/** A finance product row -> the reference's plan shape. */
const financeItem = (p) => {
  const it = p || {};
  const filled = Number(it.filled_minor || 0);
  const cap = Number(it.max_minor || 0);
  return {
    ...it,
    name: it.title,
    // the card binds src to `img`; iconurl/imageurl are used elsewhere
    img: it.image,
    iconurl: it.image,
    imageurl: it.image,
    rate: (it.rate_bps || 0) / 100,
    rate_income: (it.rate_bps || 0) / 100,
    day: it.term_days,
    min: major(it.min_minor),
    max: major(it.max_minor),
    price: major(it.min_minor),
    amount: major(it.min_minor),
    max_buy: major(it.max_minor),
    // the progress bar is bound as `100 * progress`, so this must be a 0-1
    // fraction and never undefined (NaN collapses the bar)
    progress: cap > 0 ? Math.min(1, filled / cap) : 0,
    all_buy_num: it.orders_count || 0,
    countdown: '',
    description: it.description || '',
    // the countdown is countDown(end_in, server_time); the vuapp plans have no
    // end date, so 0 makes it resolve to 00:00:00, which the screen hides
    end_in: it.end_at || 0,
    server_time: nowSec(),
    // what a minimum subscription returns over the full term
    receive: Math.round(major(it.min_minor) * ((it.rate_bps || 0) / 10000) * (it.term_days || 0) * 100) / 100,
    surplus: major(it.max_minor),
    balance: 0,
    // subscriber avatars the reference showed; no equivalent yet
    userimgurl: [],
    usernumber: 0,
    user_headimg: '',
    user_name: '',
  };
};

/** The account payload -> the reference's user-info shape. */
const userShape = (r) => {
  const res = r || {};
  const u = res.user || res;
  const c = res.counts || {};
  return {
    ...u,
    name: u.username || '',
    nickname: u.username || '',
    mobile: u.phone || '',
    imgUrl: u.avatar || '',
    headimgurl: u.avatar || '',
    money: major(u.balance_minor),
    balance: major(u.balance_minor),
    invite_code: u.invite_code || '',
    status: 1,
    // 1 marks a brand-new user; it drives the home guide overlay
    new: (c.orders || 0) === 0 ? 1 : 0,
    order_count: c.orders || 0,
    win_count: c.wins || 0,
    team_count: c.team || 0,
    // balances the reference broke out separately; the vuapp wallet is a single
    // ledger, so the withdrawable amount is the balance and the rest are zero
    cashOut: major(u.balance_minor),
    today_cost: 0,
    finance_all_price: 0,
    finance_all_income: 0,
    finance_day_income: 0,
    return_amount: 0,
    return_cap: 0,
    return_income: 0,
    return_rate: 0,
    vip_img: '',
    vip_level: u.vip_level || 0,
  };
};

/** A winner row -> the reference's "latest winners" ticker shape. */
const winnerItem = (w) => {
  const it = w || {};
  return {
    ...it,
    nickname: it.nickname || it.username || it.phone_masked || '',
    headimgurl: it.avatar || it.image || '',
    name: it.goods_title || it.title || '',
  };
};

const listOf = (r, ...keys) => {
  const res = r || {};
  for (const k of keys) if (Array.isArray(res[k])) return res[k];
  return Array.isArray(res) ? res : [];
};

/** POST /index/accountedit */
export const AccountEdit = (d = {}) => put('/api/account/username', { username: d.name || d.username });

/** POST /index/duobaoitemlistnew */
export const ActiveList = () =>
    Promise.all([get('/api/home'), get('/api/winners').catch(() => ({}))]).then(([home, win]) => {
      const newbie = listOf(home, 'newbie');
      return {
        // the newbie deal card
        runoob: newbie.length ? goodsItem(newbie[0]) : {},
        // "latest winners" ticker
        new: { list: listOf(win, 'winners').map(winnerItem) },
        // the "hot picks" strip
        zhuanqu: { list: listOf(home, 'high').map(goodsItem) },
        // the "upcoming" strip
        upcoming: listOf(home, 'latest').map(goodsItem),
        // the reference drove a banner countdown from this; no equivalent yet
        activity: { time: 0, nowtime: nowSec() },
      };
    });

/** POST /index/addressadd */
export const AddAddress = (d = {}) => post('/api/addresses', d);

/** POST /index/addorder */
export const AddOrder = (d = {}) => post('/api/orders', d);

/** POST /index/addresslist */
export const AddressList = () => get('/api/addresses');

/** POST /index/addressdel */
export const DelAddress = (d = {}) => (d.id ? del('/api/addresses/' + d.id) : Promise.resolve({}));

/** POST /index/duobaoitem */
export const DuobaoItem = (d = {}) =>
    get('/api/goods', { category: d.kind || d.category }).then((r) => {
      const list = listOf(r, 'goods').map(goodsItem);
      return { list, count: list.length };
    });

/** POST /index/duobaoitem1 */
export const DuobaoSwiperItem = () =>
    get('/api/home').then((r) => listOf(r, 'latest', 'high', 'newbie').map(goodsItem));

/** POST /index/addresschangedefault */
export const EditAccount = (d = {}) => (d.id ? put('/api/addresses/' + d.id, { ...d, is_default: 1 }) : Promise.resolve({}));

/** POST /index/addressedit */
export const EditAddress = (d = {}) => (d.id ? put('/api/addresses/' + d.id, d) : post('/api/addresses', d));

/** POST /index/kind */
export const GKind = () =>
    get('/api/goods').then((r) => {
      const cats = [];
      for (const g of listOf(r, 'goods')) if (g.category && !cats.includes(g.category)) cats.push(g.category);
      return cats.map((c) => ({ label: c.charAt(0).toUpperCase() + c.slice(1), value: c }));
    });

/** POST /index/duobaoitemlottery */
export const GetLottery = (d = {}) => (d.id ? post('/api/goods/' + d.id + '/draw', d) : Promise.resolve({ list: [] }));

/** POST /index/getlotteryresult */
export const GetResult = (d = {}) => (d.id ? get('/api/orders/' + d.id + '/ranking') : Promise.resolve({ list: [] }));

/** POST /index/duobaoitemjoinlist */
export const GoodsBuyDetail = (d = {}) => (d.id ? get('/api/goods/' + d.id) : get('/api/goods'));

/** POST /index/duobaoitemdetail */
export const GoodsDetail = (d = {}) =>
    (d.id ? get('/api/goods/' + d.id) : get('/api/goods')).then((r) => {
      const row = (r && r.goods) || r || {};
      return goodsItem(Array.isArray(row) ? row[0] : row);
    });

/** POST /index/duobaoitemhistory */
export const GoodsHisDetail = (d = {}) =>
    (d.id ? get('/api/goods/' + d.id) : get('/api/goods')).then((r) => {
      const row = (r && r.goods) || r || {};
      return goodsItem(Array.isArray(row) ? row[0] : row);
    });

/** POST /index/duobaoitemlist */
export const GoodsList = (d = {}) =>
    get('/api/goods', { category: d.category }).then((r) => {
      const list = listOf(r, 'goods').map(goodsItem);
      return { list, count: list.length };
    });

/** POST /index/duobaoitemshare */
export const GoodsShareDetail = (d = {}) =>
    (d.id ? get('/api/goods/' + d.id) : get('/api/goods')).then((r) => {
      const row = (r && r.goods) || r || {};
      return goodsItem(Array.isArray(row) ? row[0] : row);
    });

/** POST /index/index */
export const Index = () =>
    get('/api/home').then((r) => {
      const home = r || {};
      return {
        title: 'vuapp',
        bannerlist: (home.banners || []).map((b) => ({
          imageurl: b.image,
          type: b.type || '',
          url: b.link || '',
        })),
        navigationlist: home.navigation || [],
        system: home.system || { whatsapp: '', customercontent: '' },
        ...home,
      };
    });

/** POST /index/itemshare */
export const ItemShare = (d = {}) => post('/api/orders', d);

/** POST /index/login */
export const Login = (d = {}) =>
    post('/api/auth/login', { phone: d.mobile || d.phone, code: d.code, invite: d.invitecode }).then((r) => {
      if (r && r.access) setTokens(r.access, r.refresh);
      return { ...r, token: r && r.access };
    });

/** POST /index/logout */
export const Logout = () => post('/api/auth/logout', { refresh: readRefresh() }).then((r) => { clearTokens(); return r; });

/** POST /index/ordernews */
export const OrderNews = () => get('/api/notices');

/** POST /index/runoobdetail */
export const RunoobDetail = (d = {}) => get('/api/pages/' + (d.slug || d.id || 'about'));

/** POST /index/sendverify */
export const SendVerify = (d = {}) => post('/api/auth/sendverify', { phone: d.mobile || d.phone });

/** POST /index/getsystem */
export const SystemInfo = () =>
    Promise.resolve({
      title: 'vuapp',
      taskstatus: 1,
      image: '',
      version: [],
      tablist: [],
    });

/** POST /index/userbalance */
export const UserBalance = () => get('/api/wallet').then((r) => ({ ...(r || {}), money: major((r || {}).balance_minor), balance: major((r || {}).balance_minor) }));

/** POST /index/useraccount */
export const UserInfo = () => get('/api/account').then(userShape);

/** POST /index/userjoin */
export const UserJoin = (d = {}) => get('/api/orders', d);

/** POST /index/winnerlist */
export const WinnerList = (d = {}) =>
    get('/api/winners', d).then((r) => ({ list: listOf(r, 'winners').map(winnerItem) }));

/** POST /index/activitydetail */
export const activityDetail = (d = {}) => get('/api/prizes', d);

/** POST /index/addrechargepay2 */
export const addRechargePay = (d = {}) => post('/api/recharge', d);

/** POST /index/bankdel */
export const bankDel = (d = {}) => (d.id ? del('/api/beneficiaries/' + d.id) : Promise.resolve({}));

/** POST /index/banklist */
export const bankList = () =>
    get('/api/beneficiaries').then((r) => ({
      ...(r || {}),
      list: listOf(r, 'beneficiaries', 'list').map((b) => ({
        ...b,
        name: b.holder || b.name || '',
        bank_name: b.bank || b.bank_name || '',
        bank_no: b.account || b.bank_no || '',
      })),
    }));

/** POST /index/bankadd */
export const bankadd = (d = {}) => post('/api/beneficiaries', d);

/** POST /index/cashlist */
export const cashList = () =>
    get('/api/withdraw/records').then((r) => ({
      ...(r || {}),
      list: listOf(r, 'records', 'withdrawals', 'list').map((x) => ({ ...x, price: major(x.amount_minor) })),
    }));

/** POST /index/chlwhatsapp */
export const chlWhatsApp = () => get('/api/pages/support');

/** POST /index/financeBuy */
export const financeBuy = (d = {}) => post('/api/finance/order', d);

/** POST /index/financeDetail */
export const financeDetail = (d = {}) =>
    (d.id ? get('/api/finance/' + d.id) : get('/api/finance')).then((r) => {
      const row = (r && (r.product || r.products)) || r || {};
      return financeItem(Array.isArray(row) ? row[0] : row);
    });

/** POST /index/financeDetailHistory */
export const financeDetailHistory = (d = {}) =>
    (d.id ? get('/api/finance/' + d.id) : get('/api/finance')).then((r) => {
      const row = (r && (r.product || r.products)) || r || {};
      const it = financeItem(Array.isArray(row) ? row[0] : row);
      return { list: it.history || [] };
    });

/** POST /index/financeList */
export const financeList = () =>
    get('/api/finance').then((r) => ({ list: listOf(r, 'products').map(financeItem) }));

/** POST /index/financeOrderRecent */
export const financeOrderRecent = () =>
    get('/api/finance/orders/mine').then((r) => ({
      list: listOf(r, 'orders', 'products', 'list').map(financeItem),
    }));

/** POST /index/getactivity */
export const getActivity = () => get('/api/prizes');

/** POST /index/getanswer */
export const getAnswer = (d = {}) => {
    const raw = String(d.id || d.topic || '');
    const [topic, id] = raw.includes(':') ? raw.split(':') : [raw, raw];
    return get('/api/help/' + encodeURIComponent(topic))
      .then((r) => {
        const list = listOf(r, 'articles');
        const found = list.find((a) => String(a.id) === String(id)) || list[0] || {};
        return { ...found, que_info: found.body || found.content || '', que_title: found.title || '' };
      })
      .catch(() => ({ que_info: '' }));
  };

/** POST /index/gettitle */
export const getTitle = () =>
    get('/api/help').then((r) => {
      const groups = [];
      for (const a of listOf(r, 'articles')) {
        const topic = a.topic || 'general';
        let g = groups.find((x) => x.category === topic);
        if (!g) {
          g = { category: topic, image_url: '/static/image/icon_faq.png', chr: [] };
          groups.push(g);
        }
        g.chr.push({ que_id: topic + ':' + a.id, title: a.title });
      }
      return groups;
    });

/** POST /index/getUserAfs */
export const getUserAfs = () => get('/api/payments');

/** POST /index/itemdefaultaddr */
export const itemDefaultAddr = () => get('/api/addresses');

/** POST /index/itemedit */
export const itemEdit = (d = {}) => post('/api/orders', d);

/** POST /index/joinactivity */
export const joinActivity = (d = {}) => post('/api/game/play', d);

/** POST /index/luckyBuy */
export const luckyBuy = (d = {}) => post('/api/game/play', d);

/** POST /index/luckyList */
export const luckyList = () => get('/api/prizes');

/** POST /index/luckyNow */
export const luckyNow = () => get('/api/prizes');

/** POST /index/luckyOrderList */
export const luckyOrderList = () => get('/api/orders', { kind: 'lucky' });

/** POST /index/myFinanceList */
export const myFinanceList = () =>
    get('/api/finance/orders/mine').then((r) => ({
      list: listOf(r, 'orders', 'products', 'list').map(financeItem),
    }));

/** POST /index/myteam */
export const myTeam = (d = {}) =>
    get('/api/team', d).then((r) => {
      const res = r || {};
      const members = listOf(res, 'members', 'team', 'list').map((m) => ({
        ...m,
        name: m.username || m.name || '',
        nickname: m.username || '',
        headimgurl: m.avatar || '',
        mobile: m.phone || '',
        money: major(m.balance_minor),
      }));
      const direct = members.filter((m) => (m.level || 1) === 1);
      return {
        ...res,
        list: members,
        count_1: res.direct_count != null ? res.direct_count : direct.length,
        count_2: res.indirect_count != null ? res.indirect_count : members.length - direct.length,
        myachievement: major(res.my_volume_minor),
        teamachievement: major(res.team_volume_minor),
        reward: major(res.reward_minor),
      };
    });

/** POST /index/mywinner */
export const myWinner = (d = {}) =>
    get('/api/my-shares', d).then((r) => ({ list: listOf(r, 'shares', 'orders').map(goodsItem) }));

/** POST /index/itemdetail */
export const orderDetail = (d = {}) =>
    (d.id || d.dumid ? get('/api/orders/' + (d.id || d.dumid)) : get('/api/orders')).then((r) => {
      const row = (r && (r.order || r.orders)) || r || {};
      const it = goodsItem(Array.isArray(row) ? row[0] : row);
      return {
        ...it,
        dumid: it.id,
        // the detail screen reads addr.name / addr.mobile and walks logdetail
        addr: row.address || {},
        logdetail: listOf(row, 'logs', 'logdetail'),
        logcount: listOf(row, 'logs', 'logdetail').length,
        lucklottery: row.lucky_code || '',
        status: row.status || it.status || 1,
      };
    });

/** POST /index/rechargelist */
export const rechargeList = () =>
    get('/api/recharge/records').then((r) => ({
      ...(r || {}),
      list: listOf(r, 'records', 'recharges', 'list').map((x) => ({ ...x, price: major(x.amount_minor) })),
    }));

/** POST /index/systemservice */
export const systemService = () => get('/api/pages/support');

/** POST /index/taskList */
export const taskList = () =>
    get('/api/tasks').then((r) => ({
      ...(r || {}),
      list: listOf(r, 'tasks', 'list').map((t) => ({
        ...t,
        name: t.title || t.name || '',
        reward: major(t.reward_minor),
        status: t.claimed ? 2 : 1,
      })),
    }));

/** POST /index/taskReceive */
export const taskReceive = (d = {}) => (d.id ? post('/api/tasks/' + d.id + '/claim', d) : Promise.resolve({}));

/** POST /index/useraccount */
export const userAccount = () => get('/api/account').then(userShape);

/** POST /index/userconsume */
export const userConsume = () =>
    get('/api/wallet/transactions').then((r) => ({
      ...(r || {}),
      list: listOf(r, 'transactions', 'txns', 'list').map((x) => ({ ...x, price: major(x.amount_minor) })),
    }));

/** POST /index/userinvitelist */
export const userInviteList = () =>
    get('/api/referrals').then((r) => ({ list: listOf(r, 'referrals', 'list') }));

/** POST /index/userinvitetop */
export const userInviteTop = () =>
    get('/api/referrals').then((r) => {
      const res = r || {};
      const list = listOf(res, 'referrals', 'list');
      return {
        ...res,
        list,
        invite: res.total != null ? res.total : list.length,
        reward: major(res.reward_minor),
        inviteurl: res.invite_url || res.inviteurl || '',
      };
    });

/** POST /index/useritem */
export const userOrder = (d = {}) =>
    get('/api/orders', d).then((r) => {
      const list = listOf(r, 'orders').map(goodsItem);
      return { list, cardList: list, count: list.length };
    });

/** POST /index/userrebatelist */
export const userRebateList = () =>
    get('/api/wallet/transactions').then((r) => ({
      ...(r || {}),
      list: listOf(r, 'transactions', 'txns', 'list').map((x) => ({ ...x, price: major(x.amount_minor) })),
    }));

/** POST /index/usershare */
export const userShare = () =>
    get('/api/my-shares').then((r) => ({ list: listOf(r, 'shares', 'orders', 'list').map(goodsItem) }));

/** POST /index/userwithdraw */
export const userWithdraw = (d = {}) => post('/api/withdraw', d);

// --- not implemented on the vuapp backend -------------------------------
//
// These reference endpoints have no vuapp counterpart yet. They resolve to
// an empty result so the screens that call them still render.
// Resolves to an empty object rather than null: the screens read
// properties straight off the response, so `{}` degrades to empty
// state while null would throw.
const notImplemented = (name, shape) => {
  if (!notImplemented.warned) notImplemented.warned = {};
  if (!notImplemented.warned[name]) {
    notImplemented.warned[name] = true;
    console.warn('[api] ' + name + ' is not implemented on the vuapp backend');
  }
  return Promise.resolve(shape || {});
};

/** POST /index/getlotterytime (lottery countdown feed) */
export const GetTime = () => notImplemented('GetTime', { time: [] });
/** POST /index/getnumbermax (per-user slot cap) */
export const NumberMax = () => notImplemented('NumberMax', { max: 0 });
/** POST /index/addorderpay (order payment intent) */
export const addOrderPay = () => notImplemented('addOrderPay');
/** POST /index/bankedit (beneficiary edit) */
export const bankEdit = () => notImplemented('bankEdit');
/** POST /index/editAfStatus (payment method toggle) */
export const editAfStatus = () => notImplemented('editAfStatus');
/** POST /index/price (price table) */
export const gPrice = () => notImplemented('gPrice', { list: [] });
/** POST /index/paystatus (payment status poll) */
export const payStatus = () => notImplemented('payStatus');
/** POST /index/vipBuy (vip purchase) */
export const vipBuy = () => notImplemented('vipBuy');
/** POST /index/vip (vip tiers) */
export const vipLevel = () => notImplemented('vipLevel', { list: [], user_level: 0, count: 0 });
