// ORich visual assets copied into the Oriva app (apps/mobile/assets/orich).
// These are bundled locally instead of referencing the decompiler artifact tree,
// so the app owns its images and can be built/shipped independently.

export const assets = {
  logo: require('../assets/orich/logo.png'),
  loginBackground: require('../assets/orich/image/login/bg.png'),
  loginPhone: require('../assets/orich/image/login/icon_iphone.png'),
  loginInvite: require('../assets/orich/image/login/icon_invitation.png'),
  homeBackground: require('../assets/orich/image/home/bg_homepage.png'),
  hotPicks: require('../assets/orich/image/home/icon_HotPicks.png'),
  upcoming: require('../assets/orich/image/home/icon_Upcoming.png'),
  quickOrders: require('../assets/orich/image/home/icon_MyOrders.png'),
  quickRecharge: require('../assets/orich/image/home/icon_Recharge.png'),
  quickWinner: require('../assets/orich/image/home/icon_Winner.png'),
  quickSupport: require('../assets/orich/image/home/icon_Support.png'),
  groupBuy: require('../assets/orich/image/home/icon_1GroupBuy.png'),
  winnerDrawn: require('../assets/orich/image/home/icon_WinnerDrawn.png'),
  freeShipping: require('../assets/orich/image/home/icon_FreeShipping.png'),
  latestStrip: require('../assets/orich/image/home/latest.png'),
  highStrip: require('../assets/orich/image/home/high.png'),
  bannerLottery: require('../assets/orich/image/home/img_lottery.png'),
  bannerWinning: require('../assets/orich/image/home/img_Winning.png'),
  goodsOne: require('../assets/orich/image/goods/goods1.png'),
  goodsTwo: require('../assets/orich/image/goods/goods2.jpg'),
  noData: require('../assets/orich/image/nodata.png'),
  walletBackground: require('../assets/orich/image/account/bg_Wallet.png'),
  accountBackground: require('../assets/orich/image/account/bg_my.png'),
  financeBackground: require('../assets/orich/image/finance/bg_list.png'),
  inviteBackground: require('../assets/orich/image/invite/invite_bg.png'),
  faqBackground: require('../assets/orich/image/faq/bg_FAQ.png'),
  taskBackground: require('../assets/orich/image/task/task_bj.png'),
  memberBackground: require('../assets/orich/image/member/bg_vip.png'),
  gameBackground: require('../assets/orich/image/game/bg_game.png'),
  prizeBackground: require('../assets/orich/image/prize/bg_partition.png'),
  success: require('../assets/orich/image/bask/img_Successful.png'),
  paymentFailed: require('../assets/orich/image/bask/img_Paymentfail.png'),
  paytm: require('../assets/orich/image/pay/paytm.png'),
  xpay: require('../assets/orich/image/pay/xpay.png'),
  // Account (mine) page assets
  financeBackground2: require('../assets/orich/image/account/bg_finance.png'),
  rewardBackground: require('../assets/orich/image/account/bg_reward.png'),
  teamBackground: require('../assets/orich/image/account/bg_myteam.png'),
  defaultAvatar: require('../assets/orich/image/account/login3.png'),
  statusWaiting: require('../assets/orich/image/account/icon_Waiting.png'),
  statusToConfirm: require('../assets/orich/image/account/icon_ToConfirm.png'),
  statusInDelivery: require('../assets/orich/image/account/icon_InDelivery.png'),
  statusReceived: require('../assets/orich/image/account/icon_Received.png'),
  menuMyshare: require('../assets/orich/image/account/icon_Myshare.png'),
  menuFunding: require('../assets/orich/image/account/icon_Fundingrecords.png'),
  menuInvitation: require('../assets/orich/image/account/icon_Invitationrecords.png'),
  menuTeam: require('../assets/orich/image/account/icon_myteam.png'),
  menuService: require('../assets/orich/image/account/icon_Customerservice.png'),
  menuAbout: require('../assets/orich/image/account/icon_AboutUs.png'),
  iconSetup: require('../assets/orich/image/account/icon_setup.png'),
  earnRewards: require('../assets/orich/image/account/icon_Earnrewards.png'),
  shareLink: require('../assets/orich/image/account/icon_Sharelink.png'),
  iconRegistion: require('../assets/orich/image/account/icon_Registion.png'),
  vipGold: require('../assets/orich/image/account/icon_gold.png'),
  arrowRight: require('../assets/orich/image/home/icon_Arrow_right.png'),
  arrowGrey: require('../assets/orich/image/home/icon_Arrow.png'),
  categoryAll: require('../assets/orich/image/home/icon_Category.png'),
  tabs: {
    home: require('../assets/orich/image/tab/icon_home_Nav_nor.png'),
    homeActive: require('../assets/orich/image/tab/icon_home_Nav_sel.png'),
    winner: require('../assets/orich/image/tab/icon_Winner_Nav_nor.png'),
    winnerActive: require('../assets/orich/image/tab/icon_Winner_Nav_sel.png'),
    member: require('../assets/orich/image/tab/icon_vip_Nav_nor.png'),
    memberActive: require('../assets/orich/image/tab/icon_vip_Nav_sel.png'),
    task: require('../assets/orich/image/tab/icon_task_nor.png'),
    taskActive: require('../assets/orich/image/tab/icon_task_sel.png'),
    account: require('../assets/orich/image/tab/icon_Account_Nav_nor.png'),
    accountActive: require('../assets/orich/image/tab/icon_Account_Nav_sel.png'),
  },
  fonts: {
    regular: require('../assets/orich/font/Roboto-Regular-14.ttf'),
    medium: require('../assets/orich/font/Roboto-Medium-12.ttf'),
    bold: require('../assets/orich/font/Roboto-Bold-3.ttf'),
  },
} as const;
