// The reference app's shared helpers (webpack module "f16a"), kept verbatim.
// Generated by tools/orich - regenerate instead of editing.
/* eslint-disable */
import { webpackModule } from '../vendor/runtime.js';
import m_0de9 from '../vendor/0de9.js';

const deps = {
  "0de9": m_0de9,
};

const mod = webpackModule(function (t, e, s) {"use strict";(function(t){function s(t,e){if(0===arguments.length||!t)return null;var s,i=e||"{y}-{m}-{d} {h}:{i}:{s}";"object"===typeof t?s=t:("string"===typeof t&&(t=/^[0-9]+$/.test(t)?parseInt(t):t.replace(new RegExp(/-/gm),"/")),"number"===typeof t&&10===t.toString().length&&(t*=1e3),s=new Date(t));var a={y:s.getFullYear(),m:s.getMonth()+1,d:s.getDate(),h:s.getHours(),i:s.getMinutes(),s:s.getSeconds(),a:s.getDay()},n=i.replace(/{([ymdhisa])+}/g,(function(t,e){var s=a[e];return"a"===e?["\u65e5","\u4e00","\u4e8c","\u4e09","\u56db","\u4e94","\u516d"][s]:s.toString().padStart(2,"0")}));return n}function i(){uni.scanCode({success:function(e){return t("log","\u6761\u7801\u7c7b\u578b\uff1a"+e.scanType," at utils/utils.js:179"),t("log","\u6761\u7801\u5185\u5bb9\uff1a"+e.result," at utils/utils.js:180"),e.result}})}function a(t,e){var s="";s=e||document.location.toString();var i=s.split("?");if(i.length>1){for(var a="",n="",r=1;r<i.length;r++){a=i[r].split("&"),n="";for(var o=0;o<a.length;o++)if(n=a[o].split("="),null!=n&&n[0]==t)return n[1]}return""}return""}function n(t,e){var s=1e3*t-1e3*e;if(s<=0)return"00:00:00";var i=parseInt(s/1e3/60/60/24,10),a=parseInt(s/1e3/60/60%24,10),n=parseInt(s/1e3/60%60,10),o=parseInt(s/1e3%60,10);i=r(i),a=r(a),n=r(n),o=r(o);var c=24*i+parseInt(a);return"".concat(c,":").concat(n,":").concat(o)}function r(t){return t<10&&(t="0"+t),t}function o(t){uni.setClipboardData({data:t,success:function(){uni.showToast({icon:"none",title:"copied"})}})}Object.defineProperty(e,"__esModule",{value:!0}),e.parseTime=s,e.scancode=i,e.GetUrlParam=a,e.countDown=n,e.checkTime=r,e.copyString=o}).call(this,s("0de9")["default"])}, deps);

export const parseTime = mod.parseTime;
export const scancode = mod.scancode;
export const GetUrlParam = mod.GetUrlParam;
export const countDown = mod.countDown;
export const checkTime = mod.checkTime;
export const copyString = mod.copyString;

export default mod;
