package com.igexin.push.extension.distribution.gbd.c;

import android.content.Context;
import android.content.pm.PackageInfo;
import android.net.wifi.WifiManager;
import android.os.Build;
import com.igexin.push.extension.distribution.gbd.b.e;
import java.net.ServerSocket;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.atomic.AtomicBoolean;
import org.json.JSONObject;

/* JADX INFO: loaded from: classes.dex */
public class c {
    public static long A;
    public static long B;
    public static long C;
    public static String D;
    public static long E;
    public static long F;
    public static long G;
    public static int H;
    public static long J;
    public static String K;
    public static String R;
    public static String S;
    public static String Y;
    public static String Z;

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public static Context f373a;
    public static String ad;
    public static ConcurrentHashMap<String, String> ae;
    public static ConcurrentHashMap<String, String> af;
    public static String ag;
    public static List<String> ak;
    public static String av;
    public static com.igexin.push.extension.distribution.gbd.e.a b;
    public static com.igexin.push.extension.distribution.gbd.d.a c;
    public static WifiManager d;
    public static ServerSocket h;
    public static boolean i;
    public static long l;
    public static Map<String, String> s;
    public static String u;
    public static String v;
    public static String w;
    public static String y;
    public static final int e = Build.VERSION.SDK_INT;
    public static final AtomicBoolean f = new AtomicBoolean(false);
    public static volatile JSONObject g = null;
    public static long j = 0;
    public static CopyOnWriteArrayList<Integer> k = new CopyOnWriteArrayList<>();
    public static List<Long> m = new ArrayList();
    public static long n = 0;
    public static long o = 0;
    public static Map<String, com.igexin.push.extension.distribution.gbd.b.a> p = new HashMap();
    public static Map<String, Long> q = new HashMap();
    public static int r = 0;
    public static long t = 0;
    public static long x = 0;
    public static long z = 0;
    public static String I = "";
    public static long L = 0;
    public static String M = "";
    public static long N = 0;
    public static long O = 0;
    public static long P = 0;
    public static String Q = "";
    public static long T = 0;
    public static String U = "";
    public static String V = "";
    public static String W = "IKOVemN2qbN1H8oLTSin+A==";
    public static String X = "JZ3K/+Lc+pARpAzWUz/1AA==";
    public static long aa = 0;
    public static int ab = 0;
    public static long ac = 0;
    public static boolean ah = false;
    public static boolean ai = false;
    public static byte[] aj = null;
    public static long al = 0;
    public static String am = null;
    public static ConcurrentHashMap<String, e> an = new ConcurrentHashMap<>();
    public static List<String> ao = new CopyOnWriteArrayList();
    public static long ap = 0;
    public static String aq = "";
    public static String ar = "";
    public static long as = 0;
    public static String at = "";
    public static int au = -1;
    public static String aw = "";
    public static String ax = "";
    public static String ay = "";
    public static String az = "";
    public static String aA = "";
    public static long aB = 0;
    public static long aC = 0;
    public static long aD = 0;
    public static List<Integer> aE = new CopyOnWriteArrayList();
    public static List<PackageInfo> aF = null;
}
