// The reference app's vuex store, ported to vuex 4 (Vue 3).
//
// Generated by tools/orich. The getters/mutations/actions are the originals;
// only the store constructor and the API imports changed.

import { createStore } from 'vuex';
import { SystemInfo, userAccount } from '@/api/orich';

export default createStore({
  state: {
    systemInfo: '{}',
    token: uni.getStorageSync('oned_token') || '',
    language: uni.getStorageSync('language') || 'en-us',
    userInfo: '{}',
    isLogin: false,
    recommValue: true,
    clientid: '',
    takeIcon: 2,
    tabList: []
  },
  getters: {
    token: function (t) {
      return t.token;
    },
    language: function (t) {
      return t.language;
    },
    userInfo: function (t) {
      return JSON.parse(t.userInfo);
    },
    systemInfo: function (t) {
      return JSON.parse(t.systemInfo);
    },
    recommValue: function (t) {
      return t.recommValue;
    }
  },
  mutations: {
    SET_TABLIST: function (t, e) {
      t.tabList = e;
    },
    SET_TAKEICON: function (t, e) {
      t.takeIcon = e;
    },
    SET_CLIENTID: function (t, e) {
      t.clientid = e;
    },
    SET_RECOMM: function (t, e) {
      t.recommValue = e;
    },
    SET_LANGUAGE: function (t, e) {
      t.language = e;
    },
    SET_TOKEN: function (t, e) {
      t.token = e;
    },
    SET_CID: function (t, e) {
      t.cid = e;
    },
    SET_SYSTEM_INFO: function (t, e) {
      t.systemInfo = e;
    },
    SET_USER_INFO: function (t, e) {
      t.userInfo = e;
    },
    SET_ISLOGIN: function (t, e) {
      t.isLogin = e;
    }
  },
  actions: {
    setLanguage: function (t, e) {
      var s = t.commit;
      t.dispatch;
      s('SET_LANGUAGE', e);
    },
    setToken: function (t, e) {
      var s = t.commit, i = t.dispatch;
      s('SET_TOKEN', e);
      i('getUserInfo').then(function () {
        uni.setStorageSync('oned_token', e);
      });
    },
    removeToken: function (t) {
      var e = t.commit;
      e('SET_TOKEN', '');
      e('SET_USER_INFO', '{}');
      e('SET_SYSTEM_INFO', '{}');
      uni.removeStorageSync('oned_token');
    },
    getUserInfo: function (t) {
      var e = t.commit;
      return new Promise(function (t, s) {
        userAccount().then(function (s) {
          e('SET_USER_INFO', JSON.stringify(s));
          e('SET_ISLOGIN', true);
          t(s);
        }).catch(function (t) {
          e('SET_ISLOGIN', false);
          s(t);
        });
      });
    },
    checkLogin: function (e) {
      var s = e.state, i = e.dispatch;
      return new Promise(function (e, a) {
        s.isLogin ? e() : (console.log('no login store'), i('getUserInfo').then(function () {
          e();
        }).catch(function () {
          a();
        }));
      });
    },
    getSystemInfo: function (t) {
      var e = t.commit;
      return new Promise(function (t, s) {
        SystemInfo().then(function (s) {
          uni.setNavigationBarTitle({
            title: s.title
          });
          e('SET_SYSTEM_INFO', JSON.stringify(s));
          e('SET_TAKEICON', s.taskstatus);
          t(s);
        }).catch(function (t) {
          s(t);
        });
      });
    },
    setTabBarItem: function (t) {
      t.state;
    }
  }
});
